// This file is automatically generated. DO NOT EDIT.

package lldpxml

type Lldp struct {
	Interface []struct {
		Age     string `xml:"age,attr"`
		Label   string `xml:"label,attr"`
		Name    string `xml:"name,attr"`
		Rid     int    `xml:"rid,attr"`
		Via     string `xml:"via,attr"`
		Chassis struct {
			Label      string `xml:"label,attr"`
			Capability []struct {
				Enabled string `xml:"enabled,attr"`
				Label   string `xml:"label,attr"`
				Type    string `xml:"type,attr"`
			} `xml:"capability"`
			Descr struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"descr"`
			ID struct {
				Label string `xml:"label,attr"`
				Type  string `xml:"type,attr"`
				Data  string `xml:",chardata"`
			} `xml:"id"`
			MgmtIface struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"mgmt-iface"`
			MgmtIp struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"mgmt-ip"`
			Name struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"name"`
		} `xml:"chassis"`
		LldpMed struct {
			Label      string `xml:"label,attr"`
			Capability []struct {
				Available string `xml:"available,attr"`
				Label     string `xml:"label,attr"`
				Type      string `xml:"type,attr"`
			} `xml:"capability"`
			DeviceType struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"device-type"`
		} `xml:"lldp-med"`
		Port struct {
			Label       string `xml:"label,attr"`
			Aggregation *struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"aggregation"`
			AutoNegotiation *struct {
				Enabled   string `xml:"enabled,attr"`
				Label     string `xml:"label,attr"`
				Supported string `xml:"supported,attr"`
				Current   struct {
					Label string `xml:"label,attr"`
					Data  string `xml:",chardata"`
				} `xml:"current"`
			} `xml:"auto-negotiation"`
			Descr struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"descr"`
			ID struct {
				Label string `xml:"label,attr"`
				Type  string `xml:"type,attr"`
				Data  string `xml:",chardata"`
			} `xml:"id"`
			Mfs struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"mfs"`
			Ttl struct {
				Label string `xml:"label,attr"`
				Data  string `xml:",chardata"`
			} `xml:"ttl"`
		} `xml:"port"`
		UnknownTlvs *struct {
			Label      string `xml:"label,attr"`
			UnknownTlv struct {
				Label   string `xml:"label,attr"`
				Len     int    `xml:"len,attr"`
				Oui     string `xml:"oui,attr"`
				Subtype int    `xml:"subtype,attr"`
				Data    string `xml:",chardata"`
			} `xml:"unknown-tlv"`
		} `xml:"unknown-tlvs"`
		Vlan []struct {
			Label  string `xml:"label,attr"`
			Pvid   string `xml:"pvid,attr"`
			VlanID int    `xml:"vlan-id,attr"`
			Data   string `xml:",chardata"`
		} `xml:"vlan"`
	} `xml:"interface"`
}
